---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/sonar.yml

- name: Deploy Sonar
  community.kubernetes.helm:
    name: sonar
    chart_ref: stable/sonarqube
    release_namespace: default
    values_files:
      - helm-values/sonar.yml

