---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/jenkinsx.yml

- name: Deploy jenkinsx
  community.kubernetes.helm:
    name: jenkinsx
    chart_ref: stable/jenkins
    release_namespace: default

