---

- name: Check if this task are already executed before
  stat:
    path: ~/.playbooks/docker_postinstall
  register: result

- name: Add current user to docker group
  user:
    append: yes
    name: "{{ ansible_user }}"
    groups:
      - docker
  become: yes

- name: Docker config for kubelet and prometheus
  copy:
    content: { "exec-opts": ["native.cgroupdriver=cgroupfs"], "metrics-addr" : "127.0.0.1:9323", "experimental" : true }
    dest: /etc/docker/daemon.json
  become: yes
  notify:
    - restart docker
  when: result.stat.exists == false

- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
  when: result.stat.exists == false

- name: create docker cert folder
  file:
    path: /etc/docker/certs.d/registry.{{ global_domain }}:443
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0755
  become: yes

- name: docker registry cert copy
  copy:
    remote_src: yes
    src: "{{ global_cert_path }}"
    dest: /etc/docker/certs.d/registry.{{ global_domain }}:443/ca.crt
    force: yes
  become: yes
  when: hostvars['k8s-master1']['registry_crt'] is not defined

- name: Get docker ca.crt
  shell:  cat {{ global_cert_path }}
  register: registry_crt
  run_once: true
  become: yes
  when: hostvars['k8s-master1']['registry_crt'] is not defined

- name: Docker registry ca.crt, if registred before
  copy:
    content: "{{ hostvars['k8s-master1']['registry_crt'].stdout }}"
    dest: /etc/docker/certs.d/registry.{{ global_domain }}:443/ca.crt
  become: yes
  when: hostvars['k8s-master1']['registry_crt'] is defined

- name: Touch a file for prevent some tasks are executing again
  file:
    path: ~/.playbooks/docker_postinstall
    state: touch
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r" # mode= 0644 also works
