---

- name: import ssl certificate
  shell: kubectl create secret tls {{ ingress_cert_name }} --key {{ ingress_cert_key }} --cert {{ ingress_cert_path }}

- name: launch nginx ingress
  shell: helm install ingress stable/nginx-ingress

