---

- name: Download and install istioctl
  shell: |
    curl -L https://istio.io/downloadIstio | sh -


- name: Install istio with default profile
  shell: |
    bin/./istioctl manifest install --set profile=demo
  args:
    chdir: ~/istio-1.7.0
