---

- name: Download and install istioctl
  shell: |
    curl -L https://istio.io/downloadIstio | sh -


- name: Install istio with default profile
  shell: |
    yes | istio-*/bin/./istioctl manifest install --set profile=demo
