---
- hosts:
    - master
    - nodes
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: systemd_dns
    - role: base
    - role: docker
      become: true
    - role: docker_postinstall
    - role: kubernetes
      become: true
    - role: k8s
  pre_tasks:
    - name: Ensure gitmodules update
      local_action: command git submodule update --init --recursive

- hosts:
    - master
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: helm
    - role: ingress
    - role: gogs
      when: global_ci_install == '1'
    - role: concourse
      when: global_ci_install == '1'
    - role: sonar
      when: global_ci_install == '1'
    - role: kubedashboard
  pre_tasks:
    - name: Ensure gitmodules update
      local_action: command git submodule update --init --recursive
