---
- hosts:
    - master
    - nodes
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: systemd_dns
    - role: base
    - role: cert
      when: inventory_hostname == 'k8s-master1'
    - role: docker
      become: true
    - role: docker_postinstall
    - role: kubernetes
      become: true
    - role: k8s

- hosts:
    - master
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: helm
    - role: ingress
    # - role: keycloak
    #   when: global_ci_install == '1'
    # - role: gogs
    #   when: global_ci_install == '1'
    - role: registry
      when: global_ci_install == '1'
    # - role: concourse
    #   when: global_ci_install == '1'
    # - role: sonar
    #   when: global_ci_install == '1'
    - role: kubedashboard
    - role: istio
    # - role: prometheus
    # - role: grafana
    # - role: elk
