---
- hosts:
    - loadbalancer
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: systemd_dns
    - role: base
    - role: haproxy

- hosts:
    - master
    - nodes
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: systemd_dns
      tags: ['k8s']
    - role: base
      tags: ['k8s']
    - role: cert
      when: inventory_hostname == 'k8s-master1'
      tags: ['k8s']
    - role: docker
      become: true
      tags: ['k8s']
    - role: docker_postinstall
      tags: ['k8s']
    - role: kubernetes
      become: true
      tags: ['k8s']
    - role: k8s
      tags: ['k8s']

- hosts:
    - master
  serial: 1
  become: false
  strategy: linear
  roles:
    - role: helm
    - role: ingress
    - role: keycloak
      when: global_ci_install == '1'
    - role: gogs
      when: global_ci_install == '1'
    - role: registry
      when: global_ci_install == '1'
    - role: concourse
      when: global_ci_install == '1'
    - role: sonar
      when: global_ci_install == '1'
    - role: kubedashboard
    - role: prometheus
    - role: grafana
    - role: elk
