---

- name: Ensure helm-values folder is present
  file:
    path: helm-values
    state: directory
    mode: 0755

- name: Values parameters file
  template:
    src: templates/values.yml.j2
    dest: helm-values/gogs.yml

- name: launch gogs
  shell: helm install --name gogs -f helm-values/gogs.yml incubator/gogs
